### ISSUE TITLE
“Set.t” and “Map.t” combinators for Irmin.Type?

### ISSUE THREAD

**Issue by TyOverby** [mirage/repr#25]
There are the `Irmin.Merge.Set` and `Irmin.Merge.Map` functors, but no associated `Irmin.Type` functions.  From my uninformed prospective, the Merge functors appear to be impossible to use without their `Type` counterparts.  Is this so?

**Comment by samoht** [comment]
(just tried a transfer of issues between repositories and it seems to work well 😍 )
