### ISSUE TITLE
Non-finite floats are problematic in JSON codec

### ISSUE THREAD

**Issue by Ngoguey42** [mirage/repr#54]
Repr's JSON encoding currently uses `string_of_float` to encode non-finite floating point values, producing "nan", "inf", "-nan" and "-inf" strings. Unfortunately "-nan" is currently not supported during decoding.

The JSON RFC doesn't specify nans nor infinity tokens, but people out there tend to use "NaN", "Infinity" and "-Infinity", e.g. JSON5 or Yojson. 

My suggestion is to break compatibility to use the 3 above tokens and also to kill the sign when serialising a "negative nan".

**Comment by CraigFe** [comment]
This issue has a history [here](https://github.com/mirage/irmin/pull/979) and [here](https://github.com/dbuenzli/jsonm/issues/12).

I'm in favour of discarding NaN payloads (regardless, we should make some consistent choice here that preserves Float equality). I'm happy to switch the string names to be better aligned with Yojson too; I wasn't aware JSON5 handles this case, nice!

**Comment by Ngoguey42** [comment]
Thanks for the links!

I left some imprecisions in my initial message. Where repr represents non-finite floats with strings, both Yojson and JSON5 introduce new lexing rules, i.e. they change the origin JSON grammar:
- https://github.com/ocaml-community/yojson/blob/master/lib/read.mll#L187-L211
- https://github.com/json5/json5/blob/master/lib/parse.js?ts=4#L269-L277

I was naively suggesting that repr should do the same but: 1. jsonm won't allow this, 2. it may not be a great idea to emit non-standard JSON.

Anyhow, the `-nan` problem persists. Let's drop the payload at encoding time :thumbsup:.

Aligning or not the string names with Yojson seems less necessary to me now. Your call.

**Comment by CraigFe** [comment]
Ah, an extension to the JSON grammar is indeed not so useful. Let's just stick with our current string names and we can bear this in mind if we eventually switch JSON libraries.

re. `-nan`, it might be possible to use `Printf.sprintf "%F"` for this (since it avoids the `-nan` pitfall at least), but would need to look more into that.

**Comment by Ngoguey42** [comment]
Instead of relying on `sprintf` or `string_of_float`, we could just pattern match the 3 cases, as it is already done in decoding.

Encoding:
```diff
  let float e f =
    match classify_float f with
-   | FP_nan | FP_infinite -> lexeme e (`String (string_of_float f))
+   | FP_nan -> lexeme e (`String "nan")
+   | FP_infinite when Float.sign_bit f -> lexeme e (`String "-inf")
+   | FP_infinite -> lexeme e (`String "inf")
    | _ -> lexeme e (`Float f)
```

Decoding:
```
  let float e =
    lexeme e >>= function
    | `Float f -> Ok f
    | `String "nan" -> Ok Float.nan
    | `String "inf" -> Ok Float.infinity
    | `String "-inf" -> Ok Float.neg_infinity
    | l -> error e l "`Float"
```

What do you think?

**Comment by CraigFe** [comment]
Looks good to me :+1: Nice to have a close correspondence between the two.
