### ISSUE TITLE
Support getting the size of an encoded value without decoding it

### ISSUE THREAD

**Issue by CraigFe** [mirage/repr#65]
Repr currently has limited support for reasoning about the size of a value's binary encoding:

```ocaml
val size_of : 'a t -> ('a -> int option) staged
```

Given a value `v` of type `t`, `size_of t v` is the length in bytes of the binary encoding, if it's possible to pre-compute this without just computing the encoding. For encodings derived from `Repr`, this is always possible: the `None` case exists in order to support foreign encoding formats, in particular for `ocaml-git`[^1]. The motivation for this function is that it allows encoders to allocate buffers of the right size before encoding.

There's also a use-case for the inverse of this process: determining the length of an encoded value before decoding it.

```ocaml
val decode_length : 'a t -> (string -> off:int -> int) option
```

For instance, we could use this to speed up the process of reconstructing an `irmin-pack` Index, as the data file doesn't attach its own length headers to the encoded values[^2]. With access to a `decode_length`, the reconstruction can just zip along each of the values – not decoding them – and add their `(length, kind, offset)` triples to a fresh index.

Related to this, there is a third function that unifies these two for fixed-size values:

```ocaml
val static_size_of : 'a t -> int option
```

This would be useful as an assertion when constructing an index, since these must have statically-sized elements.

<hr/>

[^1]: As an aside, it's possible to weaken the type to `('a -> int) option` without breaking Irmin.
[^2]: In hindsight, perhaps we should have done that.

**Comment by Ngoguey42** [comment]
The `static_size_of` of a `Repr.int` can't be known, but we know the range for it. 

I suppose the function could take this form:
```ocaml
val static_size_of : 'a t -> [ `Unknown | `Fixed int | `Range int * int ]
```
